spring:
  application:
    name: Enotes_API_Service
  profiles:
    active: dev

# =========================
# DEV configuration
# =========================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_db_dev
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: bapurayamane123@gmail.com
    password: "crrm xutb pqpd iqyi"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

file:
  upload:
    path: notes/

email:
  send:
    from: bapurayamane123@gmail.com

# =========================
# TEST configuration
# =========================
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_db_test
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: bapurayamane123@gmail.com
    password: "crrm xutb pqpd iqyi"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

file:
  upload:
    path: notes/

email:
  send:
    from: bapurayamane123@gmail.com

# =========================
# UAT configuration
# =========================
---
spring:
  config:
    activate:
      on-profile: uat

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_db_uat
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: bapurayamane123@gmail.com
    password: "crrm xutb pqpd iqyi"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

file:
  upload:
    path: notes/

email:
  send:
    from: bapurayamane123@gmail.com

# =========================
# PROD configuration
# =========================
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_db_prod
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: bapurayamane123@gmail.com
    password: "crrm xutb pqpd iqyi"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

file:
  upload:
    path: notes/

email:
  send:
    from: bapurayamane123@gmail.com
